# Generated by Django 3.1.2 on 2020-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
