# Generated by Django 3.1.2 on 2020-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description_ca',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='description_en_us',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='description_es',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
